from app.db.base_class import Base
from app.models.series import Series
from app.models.episode import Episode
from app.models.author import Author
from app.models.publisher import Publisher
from app.models.tag import Tag
from app.models.genre import Genre
from app.models.series_author import SeriesAuthor
from app.models.series_genre import SeriesGenre
from app.models.series_tag import SeriesTag
