from app.db.base_class import Base
from app.model.series import Series
from app.model.episode import Episode
from app.model.author import Author
from app.model.publisher import Publisher
from app.model.tag import Tag
from app.model.genre import Genre
from app.model.series_author import SeriesAuthor
from app.model.series_genre import SeriesGenre
from app.model.series_tag import Seriestag
