from .series import series
from .episode import episode
from .publisher import publisher
from .author import author
from .genre import genre
from .tag import tag
from .series_author import series_author
from .series_genre import series_genre
from .series_tag import series_tag
