"""delete profile column in author table

Revision ID: 009943f92899
Revises: 8c368a0e779e
Create Date: 2021-11-09 13:43:46.504449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009943f92899'
down_revision = '8c368a0e779e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'profile_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('profile_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
