"""add column price to episode

Revision ID: 8c368a0e779e
Revises: 2480cfc5e5f9
Create Date: 2021-11-08 23:01:20.539342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c368a0e779e'
down_revision = '2480cfc5e5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'price')
    # ### end Alembic commands ###
