name: Docker Image CI

on:
  push:
    branch: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: hwc9169/nasomedia-main-service
          tag: latest
          registry: docker.io
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}